version: '3'

services:
  api:
    build: ./docker/api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data   # Map a volume for persistent storage of db.db
    depends_on:
      - nginx

  nginx:
    build: ./docker/frontend
    ports:
      - "8070:8070"
    depends_on:
      - api

