version: '3'
services:
  zombies:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - /home/ssilver/data/zombie-arcade:/app/data
    labels:
      - "traefik.http.routers.zombies.tls=true"
      - "traefik.http.routers.zombies.rule=Host(`zombies.samsilver.ca`)"
    network_mode: bridge
