networks:
  web:
    external: true

services:
  zombies:
    image: registry.samsilver.ca/zombie-arcade:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /data/zombie-arcade:/app/data
    labels:
      - "traefik.http.routers.zombies.tls=true"
      - "traefik.http.routers.zombies.rule=Host(`zombies.samsilver.ca`)"
    networks:
      - web
