name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1 

    - name: Start Deployment
      uses: wshihadeh/docker-deployment-action@v1
      with:
        remote_docker_host: git@5.161.112.116
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        deployment_mode: docker-compose
        args: up -d
        docker_prune: 'true'
        stack_file_name: docker-compose.yml
        pull_images_first: 'true'
